import { onAuthStateChanged,signInWithEmailAndPassword,signOut } from 'firebase/auth';
import { doc,getDoc,onSnapshot } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { auth,db,functions } from './src/firebase/client';

const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const FEATURES={publicLandingPageEnabled:'Public landing page',registrationsEnabled:'New registrations',loginEnabled:'User login',inventoryUpdatesEnabled:'Inventory updates',barcodeScannerEnabled:'Barcode scanner',notificationsEnabled:'Notifications',reportsEnabled:'Reports',signageEnabled:'Signage generator'};
const IMPACT={active:'Full plan access is restored immediately.', 'read-only':'Users can view and export data, but cannot add, edit or delete.',suspended:'Users can log in, see the suspension page and export their data. Inventory management is blocked.',disabled:'All business dashboard access is blocked. Existing data is retained.'};
let state={businesses:[],settings:null},saving=false,adminWatcher=null;

function toast(message,isError=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error-toast',isError);el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function date(value){const raw=value?.toDate?value.toDate():value?new Date(value):null;return raw&&!Number.isNaN(raw.valueOf())?raw.toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'}):'Never'}
function safe(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function friendly(value){return String(value||'').replaceAll('_',' ').replaceAll('-',' ')}
async function call(name,data={}){if(!functions)throw new Error('Firebase Functions are unavailable.');return (await httpsCallable(functions,name)(data)).data}
function defaults(){return {maintenanceMode:false,maintenanceMessage:'',publicLandingPageEnabled:true,registrationsEnabled:true,loginEnabled:true,inventoryUpdatesEnabled:true,barcodeScannerEnabled:true,notificationsEnabled:true,reportsEnabled:true,signageEnabled:true}}
async function verifyAdministrator(user){if(!db)return false;const token=await user.getIdTokenResult(true);if(token.claims.superAdmin!==true)return false;const ref=doc(db,'platformAdmins',user.uid),snapshot=await getDoc(ref),data=snapshot.data();if(!snapshot.exists()||data?.role!=='super_admin'||data?.active!==true)return false;adminWatcher?.();adminWatcher=onSnapshot(ref,current=>{const admin=current.data();user.getIdTokenResult(true).then(currentToken=>{if(currentToken.claims.superAdmin!==true||!current.exists()||admin?.role!=='super_admin'||admin?.active!==true){toast('Administrator access has been disabled.',true);signOut(auth)}})});return true}
async function loadDashboard(){const data=await call('ownerDashboard');state.businesses=data.businesses||[];state.settings={...defaults(),...(data.settings||{})};renderStats(data.totalUsers||0);renderBusinesses();renderRecent();renderSettings()}
function renderStats(totalUsers){const count=(field,value)=>state.businesses.filter(b=>b[field]===value).length,cards=[['Registered businesses',state.businesses.length,'All tenants'],['Active businesses',count('accessStatus','active'),'Full access'],['Suspended businesses',count('accessStatus','suspended'),'Data preserved'],['Trial accounts',count('subscriptionStatus','trial'),'Subscription'],['Past-due accounts',count('subscriptionStatus','past_due'),'Needs attention'],['Cancelled accounts',count('subscriptionStatus','cancelled'),'Retained accounts'],['Total users',totalUsers,'Firebase Authentication'],['Account warnings',state.businesses.filter(b=>['past_due','cancelled'].includes(b.subscriptionStatus)||['suspended','disabled'].includes(b.accessStatus)).length,'Needs review']];$('#stats').innerHTML=cards.map(item=>`<article class="stat"><span>${item[0]}</span><strong>${item[1]}</strong><small>${item[2]}</small></article>`).join('')}
function businessRow(b){const access=(b.accessStatus||'active').replace('_','-'),subscription=b.subscriptionStatus||'trial';return `<tr><td><b>${safe(b.name)}</b><small>${safe(b.id)}</small></td><td>${safe(b.ownerName||'Not recorded')}</td><td>${safe(b.plan||'Starter')}</td><td><span class="badge ${subscription}">${safe(friendly(subscription))}</span></td><td><span class="badge ${access}">${safe(friendly(access))}</span></td><td>${Number(b.productCount)||0}</td><td>${date(b.lastActivityAt)}</td><td><button class="secondary manage" data-id="${safe(b.id)}">Manage</button></td></tr>`}
function filtered(){const query=$('#businessSearch').value.trim().toLowerCase(),filter=$('#statusFilter').value;return state.businesses.filter(b=>(!query||`${b.name} ${b.ownerName||''} ${b.id}`.toLowerCase().includes(query))&&(filter==='all'||((b.accessStatus||'active').replace('_','-'))===filter))}
function renderBusinesses(){$('#businessRows').innerHTML=filtered().map(businessRow).join('')||'<tr><td colspan="8">No businesses match this view.</td></tr>'}
function renderRecent(){$('#recentBusinesses').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Business</th><th>Owner</th><th>Plan</th><th>Subscription</th><th>Access</th><th>Products</th><th>Last activity</th><th></th></tr></thead><tbody>${state.businesses.slice(0,8).map(businessRow).join('')}</tbody></table></div>`}
function renderSettings(){const settings=state.settings||defaults();$('#maintenanceMode').checked=Boolean(settings.maintenanceMode);$('#maintenanceMessage').value=settings.maintenanceMessage||'';$('#estimatedReturnAt').value=settings.estimatedReturnAt?.toDate?settings.estimatedReturnAt.toDate().toISOString().slice(0,16):'';$('#featureSwitches').innerHTML=Object.entries(FEATURES).map(([key,label])=>`<label class="toggle-row"><span><b>${label}</b></span><input type="checkbox" data-feature="${key}" ${settings[key]!==false?'checked':''}></label>`).join('');toggleShutdown()}
function show(view){$$('.view').forEach(element=>element.classList.toggle('active',element.id===view));$$('.nav').forEach(element=>element.classList.toggle('active',element.dataset.view===view));$('#title').textContent={overview:'Platform overview',businesses:'Business access control',platform:'Platform Control',audit:'Audit records'}[view];if(view==='audit')loadAudit()}
function openAccess(id){const business=state.businesses.find(item=>item.id===id);if(!business)return;$('#businessId').value=business.id;$('#businessName').value=business.name;$('#accessTitle').textContent=business.name;$('#accessStatus').value=(business.accessStatus||'active').replace('_','-');$('#subscriptionStatus').value=business.subscriptionStatus||'trial';$('#originalSubscription').value=business.subscriptionStatus||'trial';$('#accessReason').value='';$('#adminNote').value=business.internalNote||'';$('#effectiveAt').value='';$('#nameConfirmation').value='';updateImpact();$('#accessDialog').showModal()}
function updateImpact(){const status=$('#accessStatus').value;$('#impact').textContent=IMPACT[status];$('#nameConfirmWrap').hidden=status!=='disabled'}
function toggleShutdown(){const shutdown=$('#maintenanceMode').checked&&!$('#featureSwitches [data-feature="loginEnabled"]')?.checked;$('#shutdownField').hidden=!shutdown}
async function loadAudit(){try{const {logs}=await call('ownerAuditLogs',{limit:100});$('#auditList').innerHTML=logs.map(log=>`<div class="audit-item"><b>${safe(log.action)}${log.businessName?' · '+safe(log.businessName):''}</b><small>${date(log.createdAt)} · Admin ${safe(log.adminUid)} · ${safe(log.reason||'No reason recorded')}</small></div>`).join('')||'No administrator actions recorded.'}catch(error){toast(error.message||'Unable to load audit history.',true)}}
function setBusy(button,busy){button.disabled=busy;button.dataset.label||=button.textContent;button.textContent=busy?'Saving…':button.dataset.label}
function confirmChange(title,message){return new Promise(resolve=>{const dialog=$('#confirmDialog');$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=message;const finish=value=>{dialog.close();$('#confirmYes').onclick=null;$('#confirmNo').onclick=null;resolve(value)};$('#confirmYes').onclick=()=>finish(true);$('#confirmNo').onclick=()=>finish(false);dialog.showModal()})}

if(!auth||!db){$('#authError').textContent='Firebase environment variables are not configured.'}else onAuthStateChanged(auth,async user=>{adminWatcher?.();adminWatcher=null;$('#authGate').hidden=false;$('#ownerApp').hidden=true;if(!user)return;try{if(!await verifyAdministrator(user)){await signOut(auth);$('#authError').textContent='This account is not authorised for owner administration.';return}$('#authGate').hidden=true;$('#ownerApp').hidden=false;await loadDashboard()}catch(error){await signOut(auth);$('#authError').textContent='Administrator access could not be verified.';toast(error.message||'Permission check failed.',true)}});
$('#ownerLogin').onsubmit=async event=>{event.preventDefault();$('#authError').textContent='';const button=event.submitter;setBusy(button,true);try{if(!auth)throw new Error('Firebase is unavailable.');await signInWithEmailAndPassword(auth,event.currentTarget.email.value,event.currentTarget.password.value)}catch{$('#authError').textContent='Sign-in failed or this account is not authorised.'}finally{setBusy(button,false)}};
$('#signOut').onclick=()=>auth&&signOut(auth);$$('.nav').forEach(button=>button.onclick=()=>show(button.dataset.view));
document.addEventListener('click',event=>{const target=event.target;if(!(target instanceof HTMLElement))return;if(target.dataset.open)show(target.dataset.open);if(target.classList.contains('manage'))openAccess(target.dataset.id);if(target.hasAttribute('data-close'))$('#accessDialog').close()});
$('#businessSearch').oninput=renderBusinesses;$('#statusFilter').onchange=renderBusinesses;$('#accessStatus').onchange=updateImpact;
$('#accessForm').onsubmit=async event=>{event.preventDefault();if(saving)return;const status=$('#accessStatus').value,name=$('#businessName').value,id=$('#businessId').value,reason=$('#accessReason').value.trim(),subscription=$('#subscriptionStatus').value;if(status==='disabled'&&$('#nameConfirmation').value!==name){toast('Type the exact business name to continue.',true);return}if(!await confirmChange('Confirm business access change',`${IMPACT[status]} This will affect ${name} immediately.`))return;saving=true;const button=$('#confirmAccess');setBusy(button,true);try{await call('setBusinessAccess',{businessId:id,accessStatus:status,reason,note:$('#adminNote').value,effectiveAt:$('#effectiveAt').value||null,confirmation:$('#nameConfirmation').value});if(subscription!==$('#originalSubscription').value)await call('setSubscriptionStatus',{businessId:id,subscriptionStatus:subscription,reason});$('#accessDialog').close();await loadDashboard();toast('Business account updated.')}catch(error){toast(error.message||'Business update failed.',true)}finally{saving=false;setBusy(button,false)}};
$('#platformForm').onchange=toggleShutdown;
$('#platformForm').onsubmit=async event=>{event.preventDefault();if(saving)return;const values=Object.fromEntries($$('[data-feature]').map(input=>[input.dataset.feature,input.checked])),maintenanceMode=$('#maintenanceMode').checked,shutdown=maintenanceMode&&!values.loginEnabled;if(!await confirmChange('Confirm platform change',maintenanceMode?'Normal users will see the maintenance screen. Owner administration remains available.':'The selected platform availability settings will take effect immediately.'))return;if(shutdown&&$('#shutdownConfirmation').value!=='SHUT DOWN STOCKGUARD'){toast('Type SHUT DOWN STOCKGUARD for the additional shutdown confirmation.',true);return}saving=true;setBusy(event.submitter,true);try{await call('updatePlatformSettings',{maintenanceMode,maintenanceMessage:$('#maintenanceMessage').value,estimatedReturnAt:$('#estimatedReturnAt').value||null,...values,reason:$('#platformReason').value,shutdownConfirmation:$('#shutdownConfirmation').value});await loadDashboard();$('#platformReason').value='';$('#shutdownConfirmation').value='';toast('Platform controls updated.')}catch(error){toast(error.message||'Platform update failed.',true)}finally{saving=false;setBusy(event.submitter,false)}};
$('#refreshAudit').onclick=loadAudit;
