import type { Timestamp } from 'firebase/firestore';
export type Role='owner'|'manager'|'employee';
export type AccessStatus='active'|'read-only'|'suspended'|'disabled';
export type SubscriptionStatus='trial'|'active'|'past-due'|'suspended'|'cancelled';
export interface Membership{id:string;businessId:string;userId:string;role:Role;status:'active'|'invited'|'disabled';createdAt?:Timestamp;updatedAt?:Timestamp}
export interface UserProfile{id:string;displayName:string;email:string;phone?:string;termsAcceptedAt?:Timestamp;privacyAcceptedAt?:Timestamp}
export interface Business{id:string;businessId:string;name:string;ownerName:string;type:string;email:string;phone:string;location:string;employeeCount:number;timezone:'Africa/Johannesburg';currency:'ZAR';warningPeriods:{critical:number;urgent:number;expiringSoon:number;watchList:number};discounts:{soon:number;urgent:number;critical:number};createdAt?:Timestamp;updatedAt?:Timestamp}
export interface Product{id:string;businessId:string;name:string;normalizedName:string;barcode:string;sku:string;category:string;supplier:string;imageUrl:string;sellingPrice:number;costPrice:number;minimumStockLevel:number;storageLocation:string;notes:string;unit:string;archived:boolean;createdBy:string;updatedBy:string;createdAt?:Timestamp;updatedAt?:Timestamp}
export interface Batch{id:string;businessId:string;productId:string;batchNumber:string;quantity:number;dateReceived:string|null;expiryDate:string;branchId:string|null;costPrice:number;sellingPrice:number;createdBy:string;createdAt?:Timestamp;updatedAt?:Timestamp}
export interface StockAction{id:string;businessId:string;productId:string;batchId:string;type:'discount'|'transfer'|'return'|'donate'|'internal-use'|'sold'|'disposed'|'assign';quantity:number;employeeId?:string;notes:string;valueSaved:number;valueLost:number;status:'pending-approval'|'approved'|'completed';createdBy:string;createdAt?:Timestamp;updatedAt?:Timestamp}
export interface Task{id:string;businessId:string;title:string;instructions:string;assignedTo:string;branchId:string;storageArea:string;dueAt:string;status:'open'|'in-progress'|'completed';completedAt?:Timestamp;completedBy?:string;createdAt?:Timestamp;updatedAt?:Timestamp}
