import { initializeApp,getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';
import { getFunctions } from 'firebase/functions';
import { env,firebaseReady } from '../config/env';
const config={apiKey:env.VITE_FIREBASE_API_KEY,authDomain:env.VITE_FIREBASE_AUTH_DOMAIN,projectId:env.VITE_FIREBASE_PROJECT_ID,storageBucket:env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:env.VITE_FIREBASE_APP_ID};
export const firebaseApp=firebaseReady?(getApps()[0]??initializeApp(config)):null;
export const auth=firebaseApp?getAuth(firebaseApp):null;
export const db=firebaseApp?getFirestore(firebaseApp):null;
export const storage=firebaseApp?getStorage(firebaseApp):null;
export const functions=firebaseApp?getFunctions(firebaseApp,'us-central1'):null;
