import { useState,type FormEvent } from 'react';
import { createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signInWithEmailAndPassword,updateProfile } from 'firebase/auth';
import { Navigate } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { auth } from '../firebase/client';
import { usePlatformStatus } from '../platform/usePlatformStatus';

type Mode='login'|'register'|'reset';

export function AuthPage(){
  const {user}=useAuth(),platform=usePlatformStatus();
  const [mode,setMode]=useState<Mode>('login'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  if(user)return <Navigate to={user.emailVerified?'/':'/verify-email'} replace/>;
  const registrationBlocked=platform?.registrationsEnabled===false,loginBlocked=platform?.loginEnabled===false;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');setBusy(true);const data=new FormData(event.currentTarget),email=String(data.get('email')).trim(),password=String(data.get('password')||'');try{if(!auth)throw new Error('Firebase environment variables are not configured.');if(mode==='login'&&loginBlocked)throw new Error('User login is temporarily unavailable.');if(mode==='register'&&registrationBlocked)throw new Error('New registrations are temporarily unavailable.');if(mode==='reset'){await sendPasswordResetEmail(auth,email);setMessage('Password reset email sent.');return}if(mode==='register'){if(!data.get('terms')||!data.get('privacy'))throw new Error('Accept the Terms and Privacy Policy to continue.');const credential=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(credential.user,{displayName:String(data.get('name')).trim()});sessionStorage.setItem('stockguard-legal-acceptance',JSON.stringify({terms:true,privacy:true,acceptedAt:new Date().toISOString()}));await sendEmailVerification(credential.user);return}await signInWithEmailAndPassword(auth,email,password)}catch(cause){setError(cause instanceof Error?cause.message:'Authentication failed.')}finally{setBusy(false)}}
  return <main className="auth-page"><section className="auth-brand"><span className="brand-mark">SG</span><p className="eyebrow">StockGuard</p><h1>Know what expires next. Protect every rand.</h1><p>SMART INVENTORY &amp; EXPIRY MANAGEMENT.</p></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><p className="eyebrow">Secure access</p><h2>{mode==='login'?'Welcome back':mode==='register'?'Create your account':'Reset your password'}</h2>{mode==='register'&&registrationBlocked&&<p className="error">New registrations are temporarily unavailable.</p>}{mode==='login'&&loginBlocked&&<p className="error">User login is temporarily unavailable. Owner administration remains accessible.</p>}{mode==='register'&&<label className="field">Your full name<input name="name" autoComplete="name" required maxLength={100}/></label>}<label className="field">Email<input name="email" type="email" autoComplete="username" required/></label>{mode!=='reset'&&<label className="field">Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={8} required/></label>}{mode==='register'&&<><label><input name="terms" type="checkbox" required/> I accept the Terms and Conditions.</label><label><input name="privacy" type="checkbox" required/> I accept the Privacy Policy.</label></>}<p className="error" role="alert">{error}</p><p role="status">{message}</p><div className="auth-actions"><button className="button" disabled={busy||(mode==='login'&&loginBlocked)||(mode==='register'&&registrationBlocked)}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Register':'Send reset email'}</button>{mode!=='login'&&<button type="button" className="button secondary" onClick={()=>setMode('login')}>Back to login</button>}</div>{mode==='login'&&<div className="auth-actions"><button type="button" className="button secondary" disabled={registrationBlocked} onClick={()=>setMode('register')}>Create account</button><button type="button" className="button secondary" onClick={()=>setMode('reset')}>Forgot password?</button></div>}</form></section></main>
}
