import { useEffect,useState } from 'react';
import { doc,onSnapshot } from 'firebase/firestore';
import { Navigate,Outlet } from 'react-router-dom';
import { useAuth } from './AuthProvider';
import { db } from '../firebase/client';
import './account-state.css';
type Access='active'|'read-only'|'suspended'|'disabled';
type Platform={maintenanceMode?:boolean;maintenanceMessage?:string;features?:{login?:boolean}};
export function BusinessRoute(){const {user,membership,loading}=useAuth();const [access,setAccess]=useState<Access|null>(null),[platform,setPlatform]=useState<Platform|null>(null);useEffect(()=>{if(!db||!membership)return;const offAccess=onSnapshot(doc(db,'businessAccessControls',membership.businessId),snap=>setAccess((snap.data()?.accessStatus as Access)||'active'));const offPlatform=onSnapshot(doc(db,'platformSettings','global'),snap=>setPlatform(snap.exists()?snap.data() as Platform:{}));return()=>{offAccess();offPlatform()}},[membership]);if(loading||membership&&(access===null||platform===null))return <main className="empty">Loading your business…</main>;if(!user?.emailVerified)return <Navigate to="/verify-email" replace/>;if(!membership)return <Navigate to="/onboarding" replace/>;if(platform?.maintenanceMode)return <AccountState title="StockGuard is under maintenance" message={platform.maintenanceMessage||'We are making scheduled improvements. Please check back soon.'}/>;if(platform?.features?.login===false)return <AccountState title="Login temporarily unavailable" message="Platform login has been paused. Your data remains protected."/>;if(access==='disabled')return <AccountState title="Business access disabled" message="Contact StockGuard support. No business data has been deleted."/>;return <>{access==='read-only'&&<div className="account-banner">Read-only mode: viewing and exports remain available; changes are blocked.</div>}{access==='suspended'&&<div className="account-banner danger-banner">Payment required: this account is suspended. You may view and export data, but cannot add, edit or delete stock.</div>}<Outlet/></>}
function AccountState({title,message}:{title:string;message:string}){const {logout}=useAuth();return <main className="auth-page"><section className="auth-brand"><span className="brand-mark">SG</span><h1>{title}</h1><p>SMART INVENTORY &amp; EXPIRY MANAGEMENT.</p></section><section className="auth-panel"><div className="auth-card"><h2>{title}</h2><p>{message}</p><button className="button" onClick={logout}>Sign out</button></div></section></main>}
